% this Matlab script collection extends the Continuous Pi Workbench, CPiWB
% author: Ross Rhodes

modelODEs = {};
ode_num = 0;

% load the CPiWB shared library
if not(libisloaded('libOdeConstruction'))
    hsffi_path = '/usr/lib64/ghc-7.8.4/include';
    loadlibrary('libOdeConstruction', 'odeConstruction.h', 'includepath', hsffi_path);
end

% call CPiWB to construct ODEs for the chosen process
[cpiwb_result, ~] = calllib('libOdeConstruction', 'callCPiWB', cpi_defs, process);

% free the shared library
unloadlibrary('libOdeConstruction');

% terminate if CPiWB encountered an error
if (strcmp(cpiwb_result, 'parse error'))
    fprintf('The CPi Workbench failed to parse your .cpi file. Please try again.');
    return;
end

% tokenize the script from CPi
tokens = strsplit(cpiwb_result, '\n');
token_num = length(tokens);

% retrieve the odes from the script
for i = 1:token_num
    chars_token = char(tokens(i));
    ode_found = findstr(chars_token, 'diff');
    if (ode_found == 1)
        ode_num = ode_num + 1;
        modelODEs{end + 1} = char(chars_token);
        ode_found = 0;
    end
end

% terminate if no ODEs were generated by CPiWB
if (isempty(modelODEs))
    fprintf(['The Continuous Pi Workbench did not produce any differential equations for ', file_name]);
    return;
end

return;