% this Matlab script collection extends the Continuous Pi Workbench, CPiWB
% author: Ross Rhodes
modelODEs = {};
ode_num = 0;
process_found = [];

while(isempty(process_found))
    % request, from the user, the process to simulate
    prompt = ['\nEnter a process name from this file for simulation.\nNote: This is case sensitive.\nEnter ''cancel'' to cancel the simulation.\n> '];
    process = input(prompt, 's');

    % if user requests to leave then return to main script
    if (strcmp(process, '') == 1 || strcmp(process, 'cancel') == 1)
        return;
    end

    % find the process definition inside the CPi file
    process_name = ['process ', process];

    def_tokens = strsplit(cpi_defs, ';');
    def_token_num = length(def_tokens);
    species = {};
    i = 1;

    while((i <= def_token_num) & (isempty(process_found))) 
        def_token = char(def_tokens(i));
        process_found = findstr(def_token, process_name);
        if (not(isempty(process_found)))
            process_def = def_token;
        end
        i = i + 1;
    end

    % report an error if the process does not exist on file
    if (isempty(process_found))
        fprintf(['Error: Process ', process, ' not found. Please try again.']);
    end
end

% load the CPiWB shared library
if not(libisloaded('libOdeConstruction'))
    hsffi_path = '/usr/lib64/ghc-7.8.4/include';
    loadlibrary('libOdeConstruction', 'odeConstruction.h', 'includepath', hsffi_path);
end

% call CPiWB to construct ODEs for the chosen process
[cpiwb_result, ~] = calllib('libOdeConstruction', 'callCPiWB', cpi_defs, process);

% free the shared library
unloadlibrary('libOdeConstruction');

% terminate if CPiWB encountered an error
if (strcmp(cpiwb_result, 'parse error'))
    fprintf('The CPi Workbench failed to parse your .cpi file. Please try again.');
    return;
end

% tokenize the script from CPi
tokens = strsplit(cpiwb_result, '\n');
token_num = length(tokens);

% retrieve the odes from the script
for i = 1:token_num
    chars_token = char(tokens(i));
    ode_found = findstr(chars_token, 'diff');
    if (ode_found == 1)
        ode_num = ode_num + 1;
        modelODEs{end + 1} = char(chars_token);
        ode_found = 0;
    end
end

% terminate if no ODEs were generated by CPiWB
if (isempty(modelODEs))
    fprintf(['The Continuous Pi Workbench did not produce any differential equations for ', file_name]);
    return;
end

char_vars = {};
sym_vars = sym([ode_num 1]);

% retrieve the variable names
for i = 1:ode_num
    ode_tokens = strsplit(modelODEs{i}, {'diff(', ','});
    char_vars{end + 1} = char(ode_tokens(2));
    sym_vars(i) = sym(char_vars{i});
end

% retrieve the initial conditions from the output script
init_conditions = [ode_num 1];

init_cond_tokens = strsplit(char(tokens(1)), {'[', ']', ';'});

for i = 1:ode_num
    init_conditions(i) = str2num(init_cond_tokens{i + 1});
end

inits = transpose(init_conditions);

% prepare the odes to be solved
sym_odes = sym([ode_num 1]);

for i = 1:ode_num
    sym_odes(i) = sym(modelODEs{i});
end

sym_odes = simplify(sym_odes);

odes = transpose(sym_odes);
vars = transpose(sym_vars);

[~, ode_exprs] = massMatrixForm(odes, vars);

% determine the time frame for the simulation
valid_time = 1;

while(valid_time == 1)
    % request a start time from the user
    time_input = [];
    while(isempty(time_input))
        prompt = '\nPlease enter the start time for the simulation.\nEnter ''cancel'' to cancel the simulation.\n> ';
        time_input = input(prompt, 's');

        if (strcmp(time_input, '') == 1 || strcmp(time_input, 'cancel') == 1)
            return;
        elseif(not(isstrprop(time_input, 'digit')))
            disp('Error: Information entered is nonnumeric.');
            time_input = [];
        else
             start_time = str2num(time_input);
        end
    end

    % request an end time from the user
    time_input = [];
    while(isempty(time_input))
        prompt = '\nPlease enter the end time for the simulation.\nEnter ''cancel'' to cancel the simulation.\n> ';
        time_input = input(prompt, 's');

        if (strcmp(time_input, '') == 1 || strcmp(time_input, 'cancel') == 1)
            return;
        elseif(not(isstrprop(time_input, 'digit')))
            disp('Error: Information entered is nonnumeric.');
            time_input = [];
        else
            end_time = str2num(time_input);
        end
    end
    
    % confirm the times provided are valid
    if (start_time >= end_time)
        fprintf('\nError: Start time exceeds end time.\n');
    else
        valid_time = 0;
    end
end

% simulate the behaviour of the system
ode_system = odeFunction(ode_exprs, vars);

[t solutions] = ode15s(ode_system, [0 end_time], inits);

% retrieve the species names to include in the simulation legend
i = 1;

while(i < def_token_num) 
    def_token = char(def_tokens(i));
    species_found = findstr(def_token, 'species ');
    if (not(isempty(species_found)))
        species_tokens = strsplit(def_token, {'species ', '('});
        species_token = species_tokens(2);
        species_in_process = findstr(process_def, char(species_token));
        if (not(isempty(species_in_process)))
            species{end + 1} = char(species_token);
        end
    end
    i = i + 1;
end

species_num = length(species);
legendString = cell(1, species_num);

species = sort(species);

for i = 1:species_num
    legendString{i} = sprintf(char(species{i}));
end

% display the simulation
start_index = 0;
end_index = length(t);

i = 1;

while (start_index == 0 & i <= end_index)
    if (start_time <= t(i))
        start_index = i;
    else
        i = i + 1;
    end
end

filename_tokens = strsplit(file_name, '.cpi');
model_name = strrep(filename_tokens(1),'_',' ');

model_name = regexprep(model_name,'(\<[a-z])','${upper($1)}');

figure('Name',char(model_name),'NumberTitle','on')
plot(t(start_index:end_index), solutions(start_index:end_index, 1:species_num), '-o') 
title(model_name);
ylabel('Species Concentration (units)');
xlabel('Time (units)');
legend('show');
legend(legendString, 'Location', 'EastOutside');

return;