function report_plan

selection = 0;

f = figure('Visible','off','Position',[600,600,300,250]);
f.MenuBar = 'none';
f.Color = [1,1,1];


bg = uibuttongroup(f,'Visible','on',...
                  'Position',[.15 0.2 0.7 0.6],...
                  'backgroundcolor','w',...
                  'BorderType','none',...
                  'Title','Please choose a process:',...
                  'SelectionChangedFcn',@bselection);
              
% Create three radio buttons in the button group.
r1 = uicontrol(bg,'Style',...
                  'radiobutton',...
                  'String','Simulate single Process',...
                  'Position',[10 85 200 30],...
                  'backgroundcolor','w',...
                  'HandleVisibility','off');
              
r2 = uicontrol(bg,'Style','radiobutton',...
                  'String','Compare Processes',...
                  'Position',[10 50 200 30],...
                  'backgroundcolor','w',...
                  'HandleVisibility','off');

btn = uicontrol('Style','pushbutton',...
           'Position',[60, 20, 80 25],...
           'String','Cancel',...
           'BackgroundColor',[1,1,1],...
           'Callback','delete(gcf)');   
     
go = uicontrol('Style','pushbutton',...
         'String','Continue',...
         'BackgroundColor',[1,1,1],...
         'Position',[160,20,80,25],...
         'Callback',@Continue_Callback);   
              
             
f.Name = 'Report Plan';
% Move the GUI to the center of the screen.
movegui(f,'center')
% Make the GUI visible.
f.Visible = 'on';

    function bselection(source,event)
       if strcmp(event.NewValue.String, 'Simulate single process')
           display(event.NewValue.String);
           selection = 0;
       else
           display(event.NewValue.String);
           selection = 1;
       end           
    end

    function Continue_Callback(source,event)
        closereq;
        if selection == 0
            report_plan_single;
        elseif selection == 1
            report_plan_multiple;
        end
    end

end